
-- Map each distinct culture value in met_artwork to a country using pattern matching.
-- Only the first/primary country match is stored (one culture -> one country).

INSERT IGNORE INTO culture_country (culture_value, country_id)
SELECT DISTINCT ma.culture, c.country_id
FROM met_artwork ma
JOIN country c ON (
  (c.country_name = 'United States' AND (ma.culture LIKE 'American%' OR ma.culture LIKE 'Anglo-American%'))
  OR (c.country_name = 'France' AND (ma.culture LIKE 'French%' OR ma.culture LIKE 'France%'))
  OR (c.country_name = 'Italy' AND (ma.culture LIKE 'Italian%' OR ma.culture LIKE 'Etruscan%' OR ma.culture LIKE 'Roman%'))
  OR (c.country_name = 'Germany' AND (ma.culture LIKE 'German%'))
  OR (c.country_name = 'United Kingdom' AND (ma.culture LIKE 'British%' OR ma.culture LIKE 'English%' OR ma.culture LIKE 'Anglo%'))
  OR (c.country_name = 'Spain' AND (ma.culture LIKE 'Spanish%'))
  OR (c.country_name = 'Netherlands' AND (ma.culture LIKE 'Dutch%' OR ma.culture LIKE 'Netherlandish%'))
  OR (c.country_name = 'Belgium' AND (ma.culture LIKE 'Belgian%' OR ma.culture LIKE 'Flemish%'))
  OR (c.country_name = 'Austria' AND (ma.culture LIKE 'Austrian%'))
  OR (c.country_name = 'Switzerland' AND (ma.culture LIKE 'Swiss%'))
  OR (c.country_name = 'Russia' AND (ma.culture LIKE 'Russian%'))
  OR (c.country_name = 'Greece' AND (ma.culture LIKE 'Greek%' OR ma.culture LIKE 'Attic%' OR ma.culture LIKE 'Corinth%'))
  OR (c.country_name = 'Turkey' AND (ma.culture LIKE 'Turkish%' OR ma.culture LIKE 'Ottoman%' OR ma.culture LIKE 'Anatol%'))
  OR (c.country_name = 'Egypt' AND (ma.culture LIKE 'Egypt%' OR ma.culture LIKE 'Coptic%'))
  OR (c.country_name = 'China' AND (ma.culture LIKE 'Chinese%' OR ma.culture LIKE 'China%'))
  OR (c.country_name = 'Japan' AND (ma.culture LIKE 'Japan%'))
  OR (c.country_name = 'India' AND (ma.culture LIKE 'Indian%' OR ma.culture LIKE 'India%' OR ma.culture LIKE 'Mughal%'))
  OR (c.country_name = 'Iran' AND (ma.culture LIKE 'Iran%' OR ma.culture LIKE 'Persian%'))
  OR (c.country_name = 'Iraq' AND (ma.culture LIKE 'Iraq%' OR ma.culture LIKE 'Mesopotam%' OR ma.culture LIKE 'Assyrian%' OR ma.culture LIKE 'Babylonian%' OR ma.culture LIKE 'Sumerian%'))
  OR (c.country_name = 'South Korea' AND (ma.culture LIKE 'Korean%' OR ma.culture LIKE 'Korea%'))
  OR (c.country_name = 'Indonesia' AND (ma.culture LIKE 'Indonesia%' OR ma.culture LIKE 'Java%' OR ma.culture LIKE 'Bali%'))
  OR (c.country_name = 'Thailand' AND (ma.culture LIKE 'Thai%'))
  OR (c.country_name = 'Cambodia' AND (ma.culture LIKE 'Cambod%' OR ma.culture LIKE 'Khmer%'))
  OR (c.country_name = 'Vietnam' AND (ma.culture LIKE 'Vietnam%'))
  OR (c.country_name = 'Myanmar' AND (ma.culture LIKE 'Burm%' OR ma.culture LIKE 'Myanmar%'))
  OR (c.country_name = 'Pakistan' AND (ma.culture LIKE 'Pakistan%' OR ma.culture LIKE 'Gandhara%'))
  OR (c.country_name = 'Afghanistan' AND (ma.culture LIKE 'Afghan%'))
  OR (c.country_name = 'Mexico' AND (ma.culture LIKE 'Mexic%' OR ma.culture LIKE 'Aztec%' OR ma.culture LIKE 'Maya%' OR ma.culture LIKE 'Olmec%' OR ma.culture LIKE 'Mixtec%' OR ma.culture LIKE 'Zapotec%'))
  OR (c.country_name = 'Peru' AND (ma.culture LIKE 'Peru%' OR ma.culture LIKE 'Inca%' OR ma.culture LIKE 'Moche%' OR ma.culture LIKE 'Nazca%' OR ma.culture LIKE 'Chavin%'))
  OR (c.country_name = 'Colombia' AND (ma.culture LIKE 'Colomb%'))
  OR (c.country_name = 'Brazil' AND (ma.culture LIKE 'Brazil%'))
  OR (c.country_name = 'Argentina' AND (ma.culture LIKE 'Argentin%'))
  OR (c.country_name = 'Canada' AND (ma.culture LIKE 'Canad%'))
  OR (c.country_name = 'Australia' AND (ma.culture LIKE 'Austral%' AND ma.culture NOT LIKE 'Austrian%'))
  OR (c.country_name = 'Nigeria' AND (ma.culture LIKE 'Nigeria%' OR ma.culture LIKE 'Yoruba%' OR ma.culture LIKE 'Igbo%' OR ma.culture LIKE 'Nok%'))
  OR (c.country_name = 'Ghana' AND (ma.culture LIKE 'Ghana%' OR ma.culture LIKE 'Akan%' OR ma.culture LIKE 'Asante%' OR ma.culture LIKE 'Ashanti%'))
  OR (c.country_name = 'Ethiopia' AND (ma.culture LIKE 'Ethiop%'))
  OR (c.country_name = 'South Africa' AND (ma.culture LIKE 'South Africa%'))
  OR (c.country_name = 'Morocco' AND (ma.culture LIKE 'Morocc%'))
  OR (c.country_name = 'Portugal' AND (ma.culture LIKE 'Portuguese%'))
  OR (c.country_name = 'Sweden' AND (ma.culture LIKE 'Swedish%'))
  OR (c.country_name = 'Denmark' AND (ma.culture LIKE 'Danish%'))
  OR (c.country_name = 'Norway' AND (ma.culture LIKE 'Norweg%'))
  OR (c.country_name = 'Ireland' AND (ma.culture LIKE 'Irish%'))
  OR (c.country_name = 'Scotland' AND (ma.culture LIKE 'Scottish%'))
  OR (c.country_name = 'Syria' AND (ma.culture LIKE 'Syria%'))
  OR (c.country_name = 'Lebanon' AND (ma.culture LIKE 'Leban%' OR ma.culture LIKE 'Phoenic%'))
  OR (c.country_name = 'Nepal' AND (ma.culture LIKE 'Nepal%'))
  OR (c.country_name = 'Sri Lanka' AND (ma.culture LIKE 'Sri Lanka%'))
  OR (c.country_name = 'Guatemala' AND (ma.culture LIKE 'Guatemal%'))
  OR (c.country_name = 'Bolivia' AND (ma.culture LIKE 'Bolivi%'))
  OR (c.country_name = 'Cuba' AND (ma.culture LIKE 'Cuba%'))
  OR (c.country_name = 'Philippines' AND (ma.culture LIKE 'Philipp%' OR ma.culture LIKE 'Filipino%'))
)
WHERE ma.culture IS NOT NULL;
